from .structural_smell_detector import StructuralSmellDetector
from .architectural_smell_detector import ArchitecturalSmellDetector
from .code_smell_detector import CodeSmellDetector
from .main import analyze_project