architectural_smells:
  GOD_OBJECT_FUNCTIONS:
    value: 20
    explanation: "Modules with more than this many functions may be trying to do too much and should be split."

  UNSTABLE_DEPENDENCY_THRESHOLD:
    value: 0.8
    explanation: "Modules with instability higher than this value may be too dependent on other modules and prone to changes."

  HUB_LIKE_DEPENDENCY_RATIO:
    value: 0.3
    explanation: "Modules connected to more than this ratio of total modules may be hub-like dependencies."

  REDUNDANT_ABSTRACTION_SIMILARITY:
    value: 0.7
    explanation: "Modules with function similarity higher than this value may be redundant abstractions."

  IMPROPER_API_USAGE_RATIO:
    value: 0.7
    explanation: "Modules with more than this ratio of repeated API calls to total calls may have improper API usage."

  CYCLIC_DEPENDENCY_MAX_LENGTH:
    value: 3
    explanation: "Cyclic dependencies involving more than this many modules are considered problematic."

structural_smells:
  NOM_THRESHOLD:
    value: 10
    explanation: "Classes with more than this many methods may be too complex."

  WMPC1_THRESHOLD:
    value: 20
    explanation: "Classes with Weighted Methods per Class (complexity-based) higher than this may be too complex."

  WMPC2_THRESHOLD:
    value: 20
    explanation: "Classes with Weighted Methods per Class (parameter-based) higher than this may have too many responsibilities."

  SIZE2_THRESHOLD:
    value: 15
    explanation: "Classes with more than this many members (methods + fields) may be too large."

  WAC_THRESHOLD:
    value: 10
    explanation: "Classes with more than this many fields may have poor encapsulation."

  LCOM_THRESHOLD:
    value: 10
    explanation: "Classes with Lack of Cohesion in Methods higher than this may need to be split."

  RFC_THRESHOLD:
    value: 20
    explanation: "Classes with Response for Class higher than this may be too coupled."

  NOCC_THRESHOLD:
    value: 10
    explanation: "Modules with more than this many classes may be too complex."

  DIT_THRESHOLD:
    value: 3
    explanation: "Classes with Depth of Inheritance Tree higher than this may be using inheritance excessively."

  LOC_THRESHOLD:
    value: 150
    explanation: "Modules with more than this many lines of code may be too large."

  MPC_THRESHOLD:
    value: 25
    explanation: "Classes with Message Passing Coupling higher than this may be too coupled."

  CBO_THRESHOLD:
    value: 5
    explanation: "Modules with Coupling Between Object Classes higher than this may be too coupled."

  NOC_THRESHOLD:
    value: 7
    explanation: "Projects with more than this many classes may be too large or complex."

  CYCLOMATIC_COMPLEXITY_THRESHOLD:
    value: 10
    explanation: "Methods with cyclomatic complexity higher than this may be too complex and hard to maintain."

  MAX_FANOUT:
    value: 15
    explanation: "Modules with more outgoing dependencies than this may be too coupled to other modules."

  MAX_FANIN:
    value: 15
    explanation: "Modules with more incoming dependencies than this may be too central or have too many responsibilities."

  MAX_FILE_LENGTH:
    value: 250
    explanation: "Files with more lines than this may be too large and should be split."

  MAX_BRANCHES:
    value: 10
    explanation: "Methods with more branches (if/else, switch cases) than this may be too complex."

  MAX_NESTING_DEPTH:
    value: 4
    explanation: "Code with nesting depth greater than this may be too complex and hard to read."


